blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using naabu
    url: https://github.com/projectdiscovery/naabu/discussions/categories/q-a
    about: Ask a question or request support for using naabu

  - name: Share idea / feature to discuss for naabu
    url: https://github.com/projectdiscovery/naabu/discussions/categories/ideas
    about: Share idea / feature to discuss for naabu

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication