name: ðŸ”¨ Build Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Todo: windows-latest, macOS-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install libpcap-dev
        run: sudo apt install libpcap-dev

      - name: Install nmap
        run: sudo apt install nmap

      - name: Build
        run: go build .
        working-directory: v2/cmd/naabu/

      - name: Test
        run: go test ./...
        working-directory: v2/

      - name: Race Condition Tests
        run: |
          go build -race .
          go run -race . -host scanme.sh
          working-directory: v2/cmd/naabu/
