name: ðŸ§ª Functional Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  functional:
    name: Functional Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest-16-cores] # Todo: windows-latest, macOS-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install required packages (libpcap-dev, nmap, simplehttpserver)
        run: |
          sudo apt install libpcap-dev
          sudo apt install nmap
          go install github.com/projectdiscovery/simplehttpserver/cmd/simplehttpserver@latest

      - name: Run the simplehttpserver on 127.0.0.1:8000
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          simplehttpserver -listen 127.0.0.1:8000 &

      - name: Functional Tests
        run: |
          chmod +x run.sh
          bash run.sh
        working-directory: v2/cmd/functional-test
